apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  namespace: petapp
  annotations:
    # AWS Load Balancer Controller annotations (example for ALB)
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # nginx ingress controller annotation (uncomment if using nginx)
    # kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: alb # Change to 'nginx' or other if not using AWS ALB Controller
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: petclinic
                port:
                  number: 80
