apiVersion: v1
kind: Service
metadata:
  name: petclinic-mysql
  namespace: petapp
  labels:
    app: petclinic
    tier: database
spec:
  ports:
    - port: 3306
  selector:
    app: petclinic
    tier: database
  clusterIP: None
