apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: petapp
type: Opaque
data:
  # Encoded "petclinic"
  MYSQL_ROOT_PASSWORD: cGV0Y2xpbmlj
  # Encoded "petclinic"
  MYSQL_DATABASE: cGV0Y2xpbmlj
  # Encoded "petclinic"
  MYSQL_USER: cGV0Y2xpbmlj
  # Encoded "petclinic"
  MYSQL_PASSWORD: cGV0Y2xpbmlj
