# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: self-hosted
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=Amit-s-Personal-Org_DevSecops_Pipeline -Dsonar.organization=amit-s-personal-org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
